# spec:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2
env:
  variables:
    TZ: "America/New_York date"
    # The remote origin that will be used if building through CodePipeline
    remote_origin: "git@github.com:bastionzero/zli.git"
  parameter-store:
    GITHUB_KEY_PATH: "/github/sshkey/path"
    SSH_KEY_PATH: "/webshell/sshkey/path"
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Install started on `date`
      # We need to 1.16 and this isnt in yum
      - wget https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.16.4.linux-amd64.tar.gz
      - echo 'export PATH=/usr/local/go/bin:$PATH' >>~/.bash_profile
      - export PATH=/usr/local/go/bin:$PATH
      - npm ci
      - npm i -g semver
  pre_build:
    commands:
      - echo Pre-Build phase...
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - aws s3 cp $(dirname $GITHUB_KEY_PATH) ~/.ssh --recursive --include ".pem"
      - aws s3 cp $(dirname $SSH_KEY_PATH) ~/.ssh --recursive --include ".pem"
      - chmod 600 ~/.ssh/*
      - ls -als ~/.ssh/*
      - eval `ssh-agent -s`
      - ssh-add ~/.ssh/*.pem
      - git submodule update --init --recursive --depth 50
  build:
    commands:
      - echo Build started on `date`
      - echo "Running eslint linter"
      - npm run lint
      - echo "Building zli"
      - npm run release-prod
      - echo "Checking VERSION is incremented"
      - MASTER_VERSION=$(git show master:package.json | jq -r .version)
      - BRANCH_VERSION=$(cat package.json| jq -r .version)
      - echo Master Version=$MASTER_VERSION, Branch Version=$BRANCH_VERSION
      - semver "$BRANCH_VERSION" -r ">$MASTER_VERSION"
      - echo "Running zli Unit Tests"
      - npm run test
