# spec:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2
env:
  variables:
    TZ: "America/New_York date"
    # The remote origin that will be used if building through CodePipeline
    remote_origin: "git@github.com:cwcrypto/thoum.git"
  parameter-store:
    GITHUB_KEY_PATH: "/github/sshkey/path"
    SSH_KEY_PATH: "/webshell/sshkey/path"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Install started on `date`
      - npm i
  pre_build:
    commands:
      - echo Pre-Build phase...
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - aws s3 cp $(dirname $GITHUB_KEY_PATH) ~/.ssh --recursive --include ".pem"
      - aws s3 cp $(dirname $SSH_KEY_PATH) ~/.ssh --recursive --include ".pem"
      - chmod 600 ~/.ssh/*
      - ls -als ~/.ssh/*
      - eval `ssh-agent -s`
      - ssh-add ~/.ssh/*.pem
  build:
    commands:
      - echo Build started on `date`
      - git submodule update --init --recursive --depth 50
      - npm run lint
      - npm run build
  post_build:
    commands:
      - echo Run unit tests started on `date`
      - echo "Running zli Unit Tests"
      - npm run test
